export const GET_CONTACTS_REQUEST = "FETCH_CONTACTS_REQUEST";
export const GET_CONTACTS_SUCCESS = "FETCH_CONTACTS_SUCCESS";
export const GET_CONTACTS_FAILED = "FETCH_CONTACTS_FAILURE";

export const GET_DETAIL_CONTACT_REQUEST = "FETCH_CONTACT_DETAIL_REQUEST";
export const GET_DETAIL_CONTACT_SUCCESS = "FETCH_CONTACT_DETAIL_SUCCESS";
export const GET_DETAIL_CONTACT_FAILED = "FETCH_CONTACT_DETAIL_FAILED";

export const ADD_CONTACT_REQUEST = "ADD_CONTACT_REQUEST";
export const ADD_CONTACT_SUCCESS = "ADD_CONTACT_SUCCESS";

export const DELETE_CONTACT_REQUEST = "DELETE_CONTACT_REQUEST";
export const DELETE_CONTACT_SUCCESS = "DELETE CONTACT_SUCCESS";

export const UPDATE_CONTACT_REQUEST = "UPDATE_CONTACT_REQUEST";
export const UPDATE_CONTACT_SUCCESS = "UPDATE_CONTACT_SUCCESS";
export const UPDATE_CONTACT_FAILED = "UPDATE_CONTACT_FAILED";
